### ISSUE TITLE
Newer BOINC versions use CDATA for messages

### ISSUE THREAD

**Issue by skybon** [suleman1971/boinctui#17]
Не так давно разработчики переключили RPC-логи на использование CDATA. В boinctui теперь сообщения клиента отображаются с мусором в виде ![CDATA[...]].

**Comment by suleman1971** [comment]
Спасибо за багрепорт. Проблему подтверждаю, исправлю.

**Comment by suleman1971** [comment]
Исправлено в версии 2.4.2
