### ISSUE TITLE
Failed to compile with ncurses on Arch

### ISSUE THREAD

**Issue by felixonmars** [suleman1971/boinctui#18]
The ncurses package on Arch provides only cursesw.h, there is no ncursesw folder under include/. I tried to replace all occurance and it compiles fine:

```
  sed -i 's_#include <ncursesw/curses.h>_#include <cursesw.h>_' src/tui-main.cpp
  sed -i 's_#include <ncursesw/_#include <_g' src/*
  sed -i 's_ncursesw/curses.h_cursesw.h_' configure.in
  sed -i 's_ncursesw/__g' configure.in
```

It would be better if this could be fixed upstream. Thanks!

**Comment by suleman1971** [comment]
This issue fixed in source now.  I hope that next version boinctui will build on Arch without  this trouble.

**Comment by felixonmars** [comment]
Thanks a lot :)

**Comment by suleman1971** [comment]
2.4.3 released. This bug was fixed. However, if this bug not go away, reopen this case please.
