### ISSUE TITLE
Invisible dialog boxes

### ISSUE THREAD

**Issue by arthurtiteica** [suleman1971/boinctui#19]
Running on Arch Linux with boinctui 2.4.2, gcc  6.1.1 and ncurses 6.0-4.

Most dialog boxes are empty, just the border and no content.

Examples:
* the initial connect to host dialog
* the Add project dialog box
* the Configure hosts list

![Screenshot](http://i.imgur.com/uKl9Zut.png)

**Comment by suleman1971** [comment]
What type and version of you terminal?

**Comment by arthurtiteica** [comment]
None of the terminals I tried work.

I tested the standard linux console (Alt+F1-F6), konsole 16.07, xterm 325 and gnome-terminal 3.20.2 and tmux inside konsole.

The $TERM variable in them goes from screen to xterm to xterm-256color.

**Comment by suleman1971** [comment]
I think "xterm-256color" is the root of this trouble. Try run boinctui with "linux" terminal:
export TERM=linux; boinctui

**Comment by arthurtiteica** [comment]
I just tried but unfortunately there's no change.

**Comment by suleman1971** [comment]
2.4.3 released. This bug was fixed. However, if this bug not go away, reopen this case please.

**Comment by arthurtiteica** [comment]
Sorry there is no change with 2.4.3.

Is there anything I could do to help? Build with some debug flags or anything else?

**Comment by suleman1971** [comment]
May be this bug is not boinctui exclusive. Try run other ncurses based apps, such as htop, alsamixer and so on. Moreover run colortest-16, colortest-16b and colortest-256 tools.

**Comment by arthurtiteica** [comment]
Yes, I use mc and htop daily and I couldn't spot any issues with them.

Maybe it helps... in boinctui there are some working dialog boxes: the About dialog, pressing Enter on a task.

**Comment by suleman1971** [comment]
I published some fixes for arch linux, but not sure what are will fix your issue. Please clone source from git ,build and test it:

git clone https://github.com/suleman1971/boinctui boinctui
autoconf
./configure --without-gnutls
make

I'll release fixed version after your confirmation.

**Comment by arthurtiteica** [comment]
Thanks for your fixes.

There is definitely some progress because now most dialogs seem to work fine.

There are still some projects that show an empty dialog box (ex 'Moo! wrapper' or 'PrimeGrid') but upon testing I've come to think they might be related to some localization/language issue outside of boinctui.

I'll test some more and let you know.

**Comment by suleman1971** [comment]
Thanks. I can see empty "add project" forms for some projects (SETI, PrimeGrid Enstein and others) now.

**Comment by suleman1971** [comment]
New fixes commited. I tested "add project" form for all available projects, and as I can see, it work good inside my arch sandbox. You can update from git and rebuild fixed version.

**Comment by arthurtiteica** [comment]
Sorry for the late reply.

I just tested the latest changes and yes I confirm that everything works.

Thank you again.

**Comment by arthurtiteica** [comment]
Hi, could you please make a release with these changes if there are no other pressing issues.

Thanks

**Comment by suleman1971** [comment]
Hi. I intent to fix clang build issue and release both fixes after several days.

**Comment by suleman1971** [comment]
Version 2.4.4 released.
