### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by chrstphrchvz** [suleman1971/boinctui#29]
GNU GPL-licensed projects **are not allowed** to be distributed without a copy of the the GPL. 
A license file containing the GPLv3 needs to be added. From https://www.gnu.org/licenses/gpl-faq.html#WhyMustIInclude:

> **Why does the GPL require including a copy of the GPL with every copy of the program?**
> 
> Including a copy of the license with the work is vital so that everyone who gets a copy of the program can know what their rights are.
> 
> It might be tempting to include a URL that refers to the license, instead of the license itself. But you cannot be sure that the URL will still be valid, five years or ten years from now. Twenty years from now, URLs as we know them today may no longer exist.
> 
> The only way to make sure that people who have copies of the program will continue to be able to see the license, despite all the changes that will happen in the network, is to include a copy of the license in the program.
> 

Additionally, the notice on each of the source files should preserve the following from the GPL notice template:
```
You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

**Comment by suleman1971** [comment]
fixed
