### ISSUE TITLE
I want to be able to add projects directly from url.

### ISSUE THREAD

**Issue by kotenok2000** [suleman1971/boinctui#33]

**Comment by suleman1971** [comment]
"Add Project by URL" implemented in 2.5.1 version of boinctui.

**Comment by kotenok2000** [comment]
Ubuntu 20:04 repository only has 2.5.0 version.

**Comment by suleman1971** [comment]
2.5.1 not in Ubuntu yet. New version of boinctui will be accepted to next version of Ubuntu after several months only. 
You can build 2.5.1 for Ubuntu 20.04 from source yourself, if necessary.
