### ISSUE TITLE
Ability to open hosts at startup 

### ISSUE THREAD

**Issue by pataquets** [suleman1971/boinctui#39]
I'd like to run `boinctui` from command line opening a specific host specifying it from command line.
This could be broken in two different (complementary) approaches:
* Ability to pass host and pass as command line switches
* Detect a `/var/lib/boinc/` directory and use the files there to open localhost if some `--localhost` switch passed.

**Comment by suleman1971** [comment]
Implemented in boinctui 2.7.0



boinctui --help

usage: 
  boinctui [--help] [--boinchost=<boinc_host_ip>:<boinc_icp_port>] [--pwd=<boinc_password>]
    -b, --boinchost      ip address and port of boinc server host
    -p, --pwd            boinc password
    -h, --help           print this help and exit`

examples: 
  boinctui --boinchost=192.168.1.123 --pwd=my_password -default port 31416 is used
  boinctui --boinchost=192.168.1.123:31416             -connect with empty password
  boinctui --boinchost=localhost                       -connect to localhost with defaul port and
                                                        password from /var/lib/boinc-client/gui_rpc_auth.cfg

**Comment by pataquets** [comment]
Awesome! Thank you very much, @suleman1971.
